### ISSUE TITLE
Инструкция

### ISSUE THREAD

**Issue by 7ife** [wasja1982/JConverter#1]
Hi. Можете обновить инструкцию, ссылка на сайт с форумом устарела, не работает.

**Comment by wasja1982** [comment]
Последняя версия инструкции по использованию конвертора: https://web.archive.org/web/20201029214953/http://www.atomx.net/forum/view_theme/235/

К сожалению, поскольку развитие CMS давно остановлено, то и конвертор тоже обновляться не будет.

**Comment by 7ife** [comment]
Спасибо. Да у меня сайт в бэкапе с 16 года, всё никак съехать не могу)
